config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    post 'visits' => 'visits#create'
    post 'contacts' => 'contacts#create'
  end

  get 'libs/tracker' => 'libs#tracker'

  get 'contacts' => 'contacts#index', as: :contacts
  get 'contacts/:id' => 'contacts#show', as: :contact

  root 'contacts#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :email, :message, presence: true
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  validates :visitor_id, :url, :datetime, presence: true

  belongs_to :visitor
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
  validates :session_id, uniqueness: true

  has_many :visits
end

app/controllers/api/api_controller.rb
class Api::ApiController < ApplicationController
  skip_before_action :verify_authenticity_token

  protected

  def current_visitor
    @current_visitor ||= Visitor.find_by_session_id current_session_id
  end

  def current_session_id
    cookies[:session_id]
  end
end

app/controllers/api/contacts_controller.rb
class Api::ContactsController < Api::ApiController
  def create
    @contact = Contact.new permited_params

    if @contact.save
      assign_email_to_current_visitor
      render json: @contact.to_json, status: 201
    else
      render json: { errors: @contact.errors }.to_json, status: 400
    end
  end

  protected

  def permited_params
    params.permit :email, :message
  end

  def assign_email_to_current_visitor
    return if current_visitor.blank?

    current_visitor.email = @contact.email
    current_visitor.save!
  end
end

app/controllers/api/visits_controller.rb
class Api::VisitsController < Api::ApiController
  def create
    @visit = Visit.new permited_params
    @visit.visitor = current_visitor

    if @visit.save
      render json: @visit.to_json, status: 201
    else
      render json: { errors: @visit.errors }.to_json, status: 400
    end
  end

  protected

  def permited_params
    params.permit :url, :datetime
  end

  def current_visitor
    create_visitor if current_session_id.blank? || super.blank?
    super
  end

  def create_visitor
    Visitor.create! session_id: set_session_id
  end

  def set_session_id
    cookies.permanent[:session_id] = random_session_id
  end

  def random_session_id
    SecureRandom.hex 32
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.all
  end

  def show
    @contact = Contact.find params[:id]
    @visits = visits
  end

  protected

  def visits
    visits = Visit.all.select 'distinct on (visits.url) visits.url, *'
    visits = visits.joins :visitor
    visits = visits.where 'visitors.email = ?', @contact.email
    visits
  end
end

app/controllers/libs_controller.rb
class LibsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def tracker
    render 'tracker.js'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/index.html.erb
<div class="ui breadcrumb">
  <a href="<%= root_path %>" class="section">Home</a>
  <i class="right chevron icon divider"></i>
  <div class="active section">Contacts</div>
</div>

<h2 chass="ui header">Contacts</h2>

<table class="ui selectable striped table">
  <thead>
    <tr>
      <th><i class="at icon"></i></th>
      <th><i class="comment outline icon"></i></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= link_to contact.email, contact_path(contact) %></td>
        <td><%= contact.message %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/contacts/show.html.erb
<div class="ui breadcrumb">
  <a href="<%= root_path %>" class="section">Home</a>
  <i class="right chevron icon divider"></i>
  <a href="<%= contacts_path %>" class="section">Contacts</a>
  <i class="right chevron icon divider"></i>
  <div class="active section"><%= @contact.email %></div>
</div>

<h2 chass="ui header">Contact</h2>

<div class="ui comments">
  <div class="comment">
    <div class="avatar">
      <i class="comment outline big icon"></i>
    </div>
    <div class="content">
      <span class="author"><%= @contact.email %></span>
      <div class="metadata">
        <span class="date"><%= time_ago_in_words @contact.created_at %></span>
      </div>
      <div class="text">
        <%= @contact.message %>
      </div>
    </div>
  </div>
</div>

<table class="ui striped table">
  <thead>
    <tr>
      <th>Visited pages</th>
    </tr>
  </thead>

  <tbody>
    <% @visits.each do |visit| %>
      <tr>
        <td><%= visit.url %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tracking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" type="text/css" class="ui" href="//oss.maxcdn.com/semantic-ui/2.1.8/semantic.min.css">

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="ui main text container">
    <%= yield %>
  </div>

</body>
</html>

app/views/libs/tracker.js.erb
var data = {
  url: window.location.href,
  datetime: (new Date).toISOString()
};

$.ajax({
  type: 'POST',
  url: '<%= api_visits_url %>',
  data: data,
  xhrFields: {
    withCredentials: true
  }
});